"""Emit the T1 post-hoc failure mode analysis.

Reads only counts already published in T1_DESCRIPTIVE_REPORT_V1.md. Computes
no metric. Group totals are sums of published counts and are labelled
"post-hoc descriptive analysis" wherever they appear.
"""
import hashlib, json, pathlib, sys

RUN = pathlib.Path("cardiosentinel-runs/phase9-t1-continuation-v1/t1-v1-measurement-continuation")
load = lambda n: json.loads((RUN / n).read_text())
dig = lambda n: hashlib.sha256((RUN / n).read_bytes()).hexdigest()

oof, subj = load("T1_OOF_RESULT.json"), load("T1_SUBJECT_EVIDENCE.json")
folds = {f["held_out_subject"]: f for f in oof["fold_summaries"]}
subs = subj["subjects"]

GROUP_A = ["ltstdb:s2005", "ltstdb:s2020", "ltstdb:s2023"]
GROUP_B = ["ltstdb:s2019", "ltstdb:s2058", "ltstdb:s2059", "ltstdb:s3072"]

o, w = [], None
o_append = o.append
def w(line=""): o_append(line)

w("# T1 Post-hoc Failure Mode Analysis and Interpretation, V1")
w()
w("**POST-HOC ANALYSIS. This document was written after the measured values were")
w("read.** It is not part of the pre-registration in")
w("`docs/T1_EVIDENCE_ANALYSIS_PLAN_V1.md` and it carries none of that document's")
w("authority. Every quantity here that is not already published in")
w("`docs/T1_DESCRIPTIVE_REPORT_V1.md` is labelled **post-hoc descriptive")
w("analysis** at the point it appears.")
w()
w("## What this document does not do")
w()
w("| | |")
w("|---|---|")
w("| Changes the primary endpoint | **No.** The registered primary remains the subject-macro mean `episode_f1` |")
w("| Changes the primary value | **No.** `episode_f1 = 0.2524` is unchanged and is not recomputed anywhere in this document |")
w("| Removes any subject | **No.** All twelve subjects remain in the registered estimate, including the three with no reference episodes |")
w("| Presents a new headline number | **No.** No alternative performance figure is computed, reported, or implied |")
w("| Recomputes any metric | **No.** Only counts already published in the descriptive report are quoted |")
w("| Alters any promoted artifact | **No.** All seven artifact digests re-verify unchanged |")
w()
w("The registered result stands exactly as reported:")
w()
w("```")
w("Subject-macro mean episode_f1 = 0.2524")
w("95% subject-bootstrap interval = [0.0826, 0.4415]")
w("```")
w()
w("This analysis explains **what the zeros inside that mean are made of**. It does")
w("not adjust the mean, and a reader who wants a single number should continue to")
w("use the registered one.")
w()
w("---")
w()
w("## 1. The seven zero-`episode_f1` subjects are two different failure modes")
w()
w("Seven of twelve subjects score `episode_f1 = 0.0000`. The descriptive report")
w("§9.1 records that these zeros arise for two incomparable reasons. This section")
w("separates them.")
w()
w("`_episode_f1` returns `2 · matched / (predicted_event_runs + reference_episodes)`")
w("and returns undefined **only** when that denominator is zero. A subject with no")
w("reference episodes but at least one predicted run therefore has a non-zero")
w("denominator, zero matches, and a defined score of exactly `0.0`.")
w()
w("### 1.1 Group A — episode-free subjects carrying a false-alarm burden")
w()
w("These subjects have **no annotated ischemic episodes at all**. Their zero is a")
w("false-alarm penalty, not a failure to detect: there was nothing available to")
w("detect.")
w()
w("| Subject | Fold | Reference episodes | Predicted runs | Unmatched predicted runs | FP windows | TP | FN | `episode_f1` |")
w("|---|---|---|---|---|---|---|---|---|")
for s in GROUP_A:
    f, e, c = folds[s], folds[s]["episode_evidence"], folds[s]["primary_confusion"]
    w(f"| `{s}` | {f['fold_index']} | **{e['reference_episodes']}** | {e['predicted_event_runs']} "
      f"| {e['unmatched_predicted_runs']} | {c['false_positive']:,} | {c['true_positive']} "
      f"| {c['false_negative']} | {subs[s]['episode_f1']:.4f} |")
w()
a_runs = sum(folds[s]["episode_evidence"]["predicted_event_runs"] for s in GROUP_A)
a_fp = sum(folds[s]["primary_confusion"]["false_positive"] for s in GROUP_A)
w("> **Post-hoc descriptive analysis.** Summing the published counts: these three")
w(f"> subjects contribute **{a_runs} predicted event runs** and **{a_fp:,} false-positive")
w("> windows** against **0 reference episodes**. No rate, ratio or normalised")
w("> quantity is derived from these sums.")
w()
w("**Interpretation.** For Group A the measurement is one of *false-alarm burden on")
w("subjects without annotated episodes*. `primary_window_mcc` is undefined for all")
w("three because the reference-positive margin is empty, and")
w("`onset_latency_seconds_median` is undefined because no episode existed to match.")
w("Both undefined values are reported as undefined in the descriptive report and")
w("are not filled here.")
w()
w("### 1.2 Group B — reference episodes present, no matched detection")
w()
w("These subjects **do** have annotated episodes. Their zero is a genuine detection")
w("failure.")
w()
w("| Subject | Fold | Reference episodes | Predicted runs | Matched | FN windows | TP | `episode_f1` |")
w("|---|---|---|---|---|---|---|---|")
for s in GROUP_B:
    f, e, c = folds[s], folds[s]["episode_evidence"], folds[s]["primary_confusion"]
    w(f"| `{s}` | {f['fold_index']} | **{e['reference_episodes']}** | {e['predicted_event_runs']} "
      f"| {e['matched_episodes']} | {c['false_negative']:,} | {c['true_positive']} "
      f"| {subs[s]['episode_f1']:.4f} |")
w()
b_ref = sum(folds[s]["episode_evidence"]["reference_episodes"] for s in GROUP_B)
b_fn = sum(folds[s]["primary_confusion"]["false_negative"] for s in GROUP_B)
w("> **Post-hoc descriptive analysis.** Summing the published counts: these four")
w(f"> subjects carry **{b_ref} reference episodes**, of which **0 were matched**, and")
w(f"> **{b_fn:,} false-negative windows**. No rate, ratio or normalised quantity is")
w("> derived from these sums.")
w()
w("**Interpretation.** For Group B the measurement is one of *complete detection")
w("failure on subjects that had annotated episodes*. Three of the four produced no")
w("predicted event run at all; `ltstdb:s3072` produced one run that did not overlap")
w("its single reference episode, so it is a matching failure rather than a silence.")
w("That distinction is visible in the published counts and is recorded here without")
w("further inference about cause.")
w()
w("### 1.3 Why the two groups must not be pooled in interpretation")
w()
w("Both groups contribute `0.0000` to the registered mean, and the mean cannot")
w("distinguish them. They answer different questions:")
w()
w("| | Group A | Group B |")
w("|---|---|---|")
w("| What the zero measures | False alarms where nothing was annotated | Failure to detect what was annotated |")
w("| Clinical failure mode | Alarm fatigue | Missed ischemia |")
w("| Would improve by | Fewer predicted runs | More predicted runs |")
w()
w("The last row is the point: the two failure modes push the operating point in")
w("**opposite directions**, so any change that improves one is liable to worsen the")
w("other. A single averaged score conceals that tension. This is an interpretive")
w("observation about the reported evidence and is not a proposal to change the")
w("estimator, the thresholds, or the registered result.")
w()
w("**No subject is excluded, and no adjusted mean is offered.** Excluding Group A")
w("would remove the false-alarm penalty and raise the headline, which is precisely")
w("the appearance a post-hoc analysis must avoid.")
w()
w("---")
w()
w("## 2. Latency interpretation")
w()
w("The descriptive report §6 and §9.2 report onset latency. This section fixes how")
w("it may be described.")
w()
w("**Definition.** `_onset_latency` computes")
w()
w("```")
w("(start_samples[run_begin] - start_samples[episode_begin]) / 250.0")
w("```")
w()
w("seconds from a matched episode's annotated onset to its matched run's onset. It")
w("is a **signed offset**, not a delay. Negative values indicate the matched")
w("predicted run started **before** the annotated episode onset.")
w()
w("**Why a negative offset does not establish anticipation.**")
w("`match_runs_to_episodes` pairs a run to an episode on **overlap alone** —")
w("`run_begin < end and begin < run_end` — with **no tolerance window** and no")
w("bound on how early a run may begin. A negative offset is therefore equally")
w("consistent with:")
w()
w("- a **persistent `EVENT` state** that was already active and merely overlaps the")
w("  annotated episode, and")
w("- a **long-duration detected run** that spans the annotated onset.")
w()
w("The artifacts record `onset_latency_seconds` but **not run durations**, so this")
w("evidence cannot separate those from genuine anticipation.")
w()
w("**Prohibited terminology.** The following must not be used of any T1 latency")
w("figure, in this repository or in any manuscript drawn from it:")
w()
w("| ❌ Prohibited | Why |")
w("|---|---|")
w("| \"early detection\" | Asserts anticipation the overlap matcher cannot establish |")
w("| \"warning time\" | Implies a clinically actionable interval before onset |")
w("| \"predictive lead time\" | Implies a validated prediction horizon |")
w()
w("**Acceptable phrasing:** *\"signed onset offset\"*, *\"median latency across")
w("detected episodes\"*, or *\"episode-level onset latency distribution among")
w("detected episodes\"*, each stating the sign convention.")
w()
w("---")
w()
w("## 3. Limitations")
w()
w("**This study does not evaluate:**")
w()
w("- **Improvement over a T1-disabled baseline.** No T1-disabled arm was run on")
w("  these held-out subjects. The study measures one configuration; it compares")
w("  nothing.")
w("- **Memory contribution.** No no-memory arm exists at the episode level.")
w("- **S4D contribution at the episode level.** The continuation measured the")
w("  retained arm only; no file in the run references the declared comparator arm")
w("  `causal_gru_longitudinal_v1`.")
w("- **External generalization.** One dataset, 12 validation subjects. EDB shares")
w("  source recordings with LTSTDB per `docs/CROSS_DATASET_PROVENANCE.md` and is")
w("  not a clean external cohort.")
w("- **Deployment performance.** No inference or serving path exists — no")
w("  `predict()`, no ONNX, no TorchScript. No latency or throughput claim about a")
w("  deployed system is available.")
w("- **Clinical utility.** Research software validated on a public dataset only.")
w("- **Causal inference.** \"Causal\" throughout this programme means temporal")
w("  non-anticipation — `t1_protocol.next_state` reads \"nothing ahead of it\" — and")
w("  never a treatment effect, intervention or counterfactual.")
w("- **Subgroup performance.** `join_performed: false`, `strata_reported: []`,")
w("  recorded before execution.")
w()
w("Each is a boundary fixed by what was run, not a gap discovered in the numbers.")
w()
w("---")
w()
w("## 4. Calibration positioning")
w()
w("U1 was a **split** retention decision, and describing it as a single retained")
w("system misstates the record.")
w()
w("**Correct statement:**")
w()
w("> U1 Platt calibration was retained to calibrate continuous scores. The")
w("> selective routing mechanism was evaluated but not retained.")
w()
w("Per `docs/U1_CALIBRATION_ROUTING_RETENTION_DECISION_V1.md`, the frozen symmetric")
w("window-level selective-routing policy at `c_star = 0.90` carries")
w("`retained: false` as the downstream or final operational router. The rejected")
w("router was preserved rather than deleted, which is a provenance decision and not")
w("a retention one.")
w()
w("**Prohibited statements:**")
w()
w("| ❌ Do not say | Why |")
w("|---|---|")
w("| \"adaptive routing implemented\" | The router exists in code but was explicitly not retained |")
w("| \"uncertainty routing deployed\" | Nothing is deployed; there is no serving path at all |")
w("| \"selective prediction system\" | Implies an operational abstention mechanism that was rejected |")
w()
w("Any document claiming that edge/cloud routing is complete is wrong and should be")
w("corrected against the retention decision.")
w()
w("---")
w()
w("## 5. Scientific boundary verification")
w()
w("Performed before this document was opened as a pull request.")
w()
w("| Boundary | Result |")
w("|---|---|")
w("| New metrics generated | **None.** Only counts already published in the descriptive report are quoted; group sums are labelled post-hoc descriptive |")
w("| New experiments executed | **None.** No run was started; none is authorized |")
w("| Test partition access | **None.** `sealed_test_state: unopened`, `test_accessed: false` in every artifact |")
w("| Threshold changes | **None.** Thresholds remain frozen per fold in the promoted fold-selection artifacts |")
w("| Model retraining | **None.** No checkpoint was read or written |")
w("| Artifact modification | **None.** All seven digests re-verify |")
w()
w("### 5.1 Artifact digests at the time of writing")
w()
w("| Artifact | SHA-256 | Unchanged |")
w("|---|---|---|")
for n in ("T1_OOF_RESULT.json","T1_SUBJECT_EVIDENCE.json","T1_BOOTSTRAP.json",
          "T1_CHALLENGE_EVIDENCE.json","T1_FINAL_CONFIGURATION.json",
          "T1_EXPERIMENT_LOCK.json","T1_V1_CONTINUATION_EXECUTION_ATTESTATION.json"):
    w(f"| `{n}` | `{dig(n)}` | ✅ |")
w()
w("The consumed development attempt remains 20 files at `2026-08-21T19:57:57`; the")
w("continuation run remains 19 files at `2026-08-22T16:18`. Neither directory was")
w("written to.")

pathlib.Path(sys.argv[1]).write_text("\n".join(o) + "\n")
print(f"wrote {sys.argv[1]}: {len(o)} lines")
